export const ACCOUNT_UPDATE = "ACCOUNT_UPDATE";
export const TOKEN_UPDATE = "TOKEN_UPDATE";
export const WEB3_LOADED = "WEB3_LOADED";
export const ACCOUNT_UPDATE_ON_DISCONNECT = "ACCOUNT_UPDATE_ON_DISCONNECT";
export const EXPLORE_SALE_TYPE_UPDATE = "EXPLORE_SALE_TYPE_UPDATE";
export const NFT_LIST_PARAMS_UPDATE = "NFT_LIST_PARAMS_UPDATE";
export const PROFILE_DATA_LOADED = "PROFILE_DATA_LOADED";
export const AUTHOR_DATA_LOADED = "AUTHOR_DATA_LOADED";
